### ISSUE TITLE
Build error when compiling OSX targeting ARM64 (error: unknown directive in BoringTLS code)

### ISSUE THREAD

**Issue by Xrayez** [godotengine/build-containers#95] opened 2021-08-25 11:12 UTC
**Branch:** main @ 5566d8c

```
[  8%] Built target rc4
make[6]: Entering directory '/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared'
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/sha/sha1-armv8.S:7:1: error: unknown directive
.hidden sha1_block_data_order
^
[  8%] Generating chacha-armv8.S
make[6]: *** [boringssl/crypto/sha/CMakeFiles/sha.dir/build.make:144: boringssl/crypto/sha/CMakeFiles/sha.dir/sha1-armv8.S.o] Error 1
make[6]: Leaving directory '/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared'
make[5]: *** [CMakeFiles/Makefile2:1188: boringssl/crypto/sha/CMakeFiles/sha.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
[  8%] Building C object boringssl/crypto/modes/CMakeFiles/modes.dir/gcm.c.o
[  8%] Building C object boringssl/crypto/CMakeFiles/crypto-objects.dir/thread.c.o
[  9%] Building ASM object boringssl/crypto/modes/CMakeFiles/modes.dir/ghashv8-armx.S.o
[ 10%] Building C object boringssl/crypto/CMakeFiles/crypto-objects.dir/thread_none.c.o
[ 10%] Building C object boringssl/crypto/CMakeFiles/crypto-objects.dir/thread_pthread.c.o
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:5:1: error: unknown directive
.code 32
^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:7:1: error: unknown directive
.hidden gcm_init_v8
^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:11:11: error: vector register expected
 vld1.64 {q9},[r1] @ load input H
          ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:12:2: error: unrecognized instruction mnemonic, did you mean: fmov, mov, movi, movk, movn, movz, smov, umov?
 vmov.i8 q11,#0xe1
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:13:25: error: unexpected symbol modifier following '@'
 vshl.i64 q11,q11,#57 @ 0xc2.0
                        ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:14:2: error: unrecognized instruction mnemonic, did you mean: ext, extr?
 vext.8 q3,q9,q9,#8
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:15:2: error: unrecognized instruction mnemonic, did you mean: shrn, sshr, ushr?
 vshr.u64 q10,q11,#63
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.SScanning dependencies of target chacha
:16:make[6]: Leaving directory '/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared'
16make[6]: Entering directory '/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared'
: error: unexpected token in argument list
 vdup.32 q9,d18[1]
               ^
[ 11%] Building C object boringssl/crypto/chacha/CMakeFiles/chacha.dir/chacha.c.o
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:17:25: error: invalid variant 't0'
 vext.8 q8,q10,q11,#8 @ t0=0xc2....01
                        ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:18:2: error: unrecognized instruction mnemonic, did you mean: shrn, sshr, ushr?
 vshr.u64 q10,q3,#63
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:19:23: error: invalid variant 'broadcast'
 vshr.s32 q9,q9,#31 @ broadcast carry bit
                      ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:20:2: error: unrecognized instruction mnemonic, did you mean: and, ands?
 vand q10,q10,q8
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:21:2: error: unrecognized instruction mnemonic, did you mean: shl, shll, sshl, ushl?
 vshl.i64 q3,q3,#1
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:22:2: error: unrecognized instruction mnemonic, did you mean: ext, extr?
 vext.8 q10,q10,q10,#8
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:23:2: error: unrecognized instruction mnemonic, did you mean: and, ands?
 vand q8,q8,q9
 ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:24:17: error: unexpected token in argument list
 vorr q3,q3,q10 @ H<<<=1
                ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:25:17: error: unexpected token in argument list
 veor q12,q3,q8 @ twisted H
                ^
/root/mono-configs/desktop-osx-arm64-release/mono/btls/build-shared/boringssl/crypto/modes/ghashv8-armx.S:26:11: error: vector register expected
 vst1.64 {q12},[r0]! @ store Htable[0]
          ^
```

My host machine has Intel CPU, if that makes a difference. Tried both under Fedora 34 host, and even Windows WSL2 Ubuntu 20.04.2.0 LTS, same results.

**Full logs:**
[xrayez-logs.tar.gz](https://github.com/godotengine/build-containers/files/7046438/xrayez-logs.tar.gz)

**Comment by qjyqjyqjyqjy** [comment] 2021-09-04 09:26
Yes, I also failed the build and look forward to fixing it.

**Comment by akien-mga** [comment] 2021-09-06 12:03
Which Mono version are you building? ARM64 support is included in latest `2020-02` branch (Preview version, I last used Mono 6.12.0.147).

**Comment by Xrayez** [comment] 2021-09-06 12:44
Using `6.12.0.147` according to `podman images`. I haven't checked out any git mono repositories manually, it's a clean build, I have even deleted all files and previous container images prior to building new ones.

**Comment by akien-mga** [comment] 2021-09-06 13:45
And which Xcode version? You need at least Xcode 12 for ARM64 support.

**Comment by Xrayez** [comment] 2021-09-06 13:50
Xcode version is the same as in `build.sh` (12.4): https://github.com/godotengine/build-containers/blob/main/build.sh#L121.

**Comment by akien-mga** [comment] 2021-09-06 14:19
Then I don't know what causes this, it seemed to work fine for me. I'll give it another try when I'm back to work next week.

**Comment by qjyqjyqjyqjy** [comment] 2021-10-10 15:17
./build.sh 3.3 mono-6-12.0.147   The OSX build failed

**Comment by akien-mga** [comment] 2021-10-10 22:43
I could reproduce it while attempting to build the new 6.12.0.158 (might also happen with 6.12.0.147, I didn't try again). I'll have to figure out what was different when I did get a working 6.12.0.147 build which I've been using for 3.4 betas...

**Comment by akien-mga** [comment] 2021-10-11 08:20
My last build of `3.x-mono-6.12.0.147` for macOS was on `2021-07-27 08:57:44 +0000 UTC`, which must be when I was working on #87. It could however be from a local Git state which was slightly different to what ended up in the PR, though nothing that would explain this error with BoringTLS IMO.

What's more likely to be problematic is godot-mono-builds updates in https://github.com/godotengine/build-containers/commit/8b32344741565e49c97c1beb078433688079865f and https://github.com/godotengine/build-containers/commit/6636cb9d01c224cbabba7937084ed3f8b3f2dc0e, respectively including https://github.com/godotengine/godot-mono-builds/pull/47 and https://github.com/godotengine/godot-mono-builds/pull/49, which are both related to BTLS.

**Comment by akien-mga** [comment] 2021-10-11 10:44
I worked around the issue with d8d17c5cae2a1bb3d0d58d262749e15b396d5cd7 by doing a local revert of the problematic changes, but this should be fixed in https://github.com/godotengine/godot-mono-builds.

**Comment by neikeq** [comment] 2021-10-15 16:20
Can reproduce with the godot-mono-builds scripts on my mac. I even have an error (albeit a different one) when building for x86_64. The solution may be to disable `--enable-btls-lib` on the macOS builds but I'm not sure if that will result in the tls issues that https://github.com/godotengine/godot-mono-builds/pull/47 and the other changes solve (solve, but still needs some tweaks, see the discussion at the end of that PR). That PR was aiming to fix the bug on Windows so not sure if the bug was also present on macOS.

**Comment by akien-mga** [comment] 2022-05-04 09:29
For now I propose reverting the problematic commit in https://github.com/godotengine/godot-mono-builds/pull/64, which is what we've been using de facto in this repo since https://github.com/godotengine/build-containers/commit/d8d17c5cae2a1bb3d0d58d262749e15b396d5cd7.

And maybe we can move this issue to godot-mono-builds to keep track of it further, even if the revert is merged as a temporary solution.

**Comment by akien-mga** [comment] 2022-05-10 09:06
Fixed by https://github.com/godotengine/godot-mono-builds/pull/65 and https://github.com/godotengine/build-containers/pull/104.

**Closed by akien-mga** 2022-05-10 09:06 UTC
Labels: bug
